[package]
name = "simplechain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
sha2 = "0.10.2"
libp2p = "0.44.0"
serde = "*"
hex = "*"
serde_json = "1.0.79"